### ISSUE TITLE
zabbix-cli dont execute via zabbix External check

### ISSUE THREAD

**Issue by invin12** [usit-gd/zabbix-cli#28]
No problem when I run zabbix-cli from shell or via cron. But when I create External check in zabbix, I've got an error

Traceback (most recent call last):
  File "/usr/local/bin/zabbix-cli", line 4, in <module>
    __import__('pkg_resources').run_script('zabbix-cli==1.6.1', 'zabbix-cli')
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 719, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1511, in run_script
    exec(script_code, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/zabbix_cli-1.6.1-py2.7.egg/EGG-INFO/scripts/zabbix-cli", line 67, in <module>
    
  File "build/bdist.linux-x86_64/egg/zabbix_cli/config.py", line 50, in __init__
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'

**Comment by usit-gd** [comment]
Thanks for the feedback.
This happens because we use the os.getenv('HOME') function to get the home directory of the user running zabbix-cli.

If the HOME environment variable is not defined, the code will raise an exception.
We have to check that HOME is defined before trying to use it.

**Comment by invin12** [comment]
Thank you/ I define HOME environment variable and it works now!
