### ISSUE TITLE
UnicodeEncodeError: 'ascii' codec can't encode characters

### ISSUE THREAD

**Issue by patsevanton** [usit-gd/zabbix-cli#38]
I have groups, hosts, templates with UTF-8 letters.
I try:
```
zabbix-cli --command "export_configuration . #all# templates"
Traceback (most recent call last):
  File "/usr/bin/zabbix-cli", line 312, in <module>
    cli.onecmd(zabbix_command)
  File "/usr/lib64/python2.7/cmd.py", line 221, in onecmd
    return func(arg)
  File "/usr/lib/python2.7/site-packages/zabbix_cli/cli.py", line 6156, in do_export_configuration
    self.generate_feedback('Error','Problems generating export file for object type [' + obj_type+ '] and object name [' + object_name_list[obj_name_key] + ']')
  File "/usr/lib/python2.7/site-packages/zabbix_cli/cli.py", line 7026, in generate_feedback
    print '\n[' + return_code.title() + ']: ' + str(message) + '\n'
UnicodeEncodeError: 'ascii' codec can't encode characters in position 74-75: ordinal not in range(128)
```

**Comment by usit-gd** [comment]
Hello

Thanks for the feedback. This is fixed in https://github.com/usit-gd/zabbix-cli/issues/32 and will be available in the next zabbix-cli release.

regards,
Rafael Martinez Guerrero
